import Head from "next/head";
import Hero from "../Compoenents/Hero";
import Layout from "../Compoenents/Layout";
import Menu from "../Compoenents/Menu";
import Service from "../Compoenents/Service";
import css from "../styles/Home.module.css"

export const getStaticProps = async()=>{
  const res = await fetch("http://localhost:8000/products")
  const data = await res.json();
  return {
    props: {
      data,
    }
  }
}

export default function Home({data}) {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        <main>
          <Hero/>
          <Service/>
          <Menu data={data}/>
          
        </main>
      </div>
      </Layout>
      
  );
}